name: rivian_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas~=2.1.1
    - pyarrow>=16
    - numpy~=1.26.2
    - scikit-learn>=1.5
    - matplotlib~=3.8.4
    - requests>=2.32
    - seaborn~=0.13.2
    - openpyxl>=3.1.0
    - pytest>=7.4.0
    - black>=23.0.0
    - ruff>=0.1.0

